# version: "4.22.1"

networks:
  local:
    driver: bridge

services:
  cache:
    image: valkey/valkey:8.0.2-alpine
    restart: unless-stopped
    # volumes:
    #  - redis-data:/var/lib/redis
    #  - redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - local

  nextcloud:
    environment:
      - REDIS_HOST=cache

  cron:
    environment:
      - REDIS_HOST=cache

  push:
    environment:
      REDIS_URL: redis://cache


